/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SpatialDetailsPanel.java
 *
 * Created on 27-Apr-2010, 08:15:19
 */

package spatialviewer;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.TableModel;

/**
 *
 * @author Richard
 */
public class SpatialDetailsPanel extends javax.swing.JPanel {
    private TableModel spatialDetailsTableModel;

    /** Creates new form SpatialDetailsPanel */
    public SpatialDetailsPanel() {
        initSpatialDetailsTableModel();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spatialDetailsTableScrollPane = new javax.swing.JScrollPane();
        spacialDetailsTable = new javax.swing.JTable();

        spacialDetailsTable.setModel(getSpatialDetailsTableModel());
        spatialDetailsTableScrollPane.setViewportView(spacialDetailsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spatialDetailsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spatialDetailsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable spacialDetailsTable;
    private javax.swing.JScrollPane spatialDetailsTableScrollPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the spatialDetailsTableModel
     */
    public TableModel getSpatialDetailsTableModel() {
        return spatialDetailsTableModel;
    }

    /**
     * @param spatialDetailsTableModel the spatialDetailsTableModel to set
     */
    public void setSpatialDetailsTableModel(TableModel spatialDetailsTableModel) {
        this.spatialDetailsTableModel = spatialDetailsTableModel;
    }

    private void initSpatialDetailsTableModel() {
        spatialDetailsTableModel = new SpatialDetailsTableModel(new ArrayList<SpatialInfo>());
    }

    public static void main(String[] args) {
        JFrame testFrame = new JFrame("Test");
        testFrame.getContentPane().add(new SpatialDetailsPanel());
        testFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        testFrame.pack();
        testFrame.setVisible(true);
    }
}
